#!/usr/bin/env python3
"""Build the RO3 Japanese XUnity dictionaries from split_1000.

The split TSV files are the canonical source. Optional files placed in
``import/`` are applied afterwards as overrides. In addition to the normal
XUnity dictionary this script creates a manual regex dictionary for strings
whose game-side placeholders are expanded before XUnity sees the text.
"""

from __future__ import annotations

import argparse
import csv
import json
import os
import re
import shutil
import sys
import tempfile
from collections import Counter
from datetime import datetime
from pathlib import Path


WORKSPACE = Path(__file__).resolve().parent
ROOT = WORKSPACE.parent
SPLIT_DIR = WORKSPACE / "split_1000"
IMPORT_DIR = WORKSPACE / "import"
MANIFEST = SPLIT_DIR / "_manifest.json"
TEXT_DIR = ROOT / "Client" / "BepInEx" / "Translation" / "ja" / "Text"
OUTPUT_FILE = TEXT_DIR / "_AutoGeneratedTranslations.txt"
CANONICAL_MANUAL_FILE = TEXT_DIR / "RO3_CanonicalTranslations.txt"
PRIORITY_OVERRIDE_FILE = TEXT_DIR / "RO3_PriorityOverrides.txt"
RUNTIME_REGEX_FILE = TEXT_DIR / "RO3_RuntimePlaceholders.txt"
CACHE_FILE = WORKSPACE / "translations_cache.json"
CONFIG_FILE = ROOT / "Client" / "BepInEx" / "config" / "AutoTranslatorConfig.ini"
LOCALIZATION_PATCH_FILE = ROOT / "Client" / "BepInEx" / "config" / "RO3.LocalizationOverrides.tsv"
LANGUAGE_KV_FILE = WORKSPACE / "LanguageKV_full_en.tsv"


# Game placeholders and formatting tokens which translations must preserve.
PROTECTED_RE = re.compile(
    r"\$\{\d+\}|@\{\d+\}|\^\{\d+\}|(?<![$@^])\{\d+\}|"
    r"%(?:\d+\$)?[sdif]|<[^>]+>|\\n"
)

# Placeholder forms which may be expanded before XUnity receives the text.
RUNTIME_TOKEN_RE = re.compile(
    r"\$\{\d+\}|@\{\d+\}|\^\{\d+\}|(?<![$@^])\{\d+\}|%(?:\d+\$)?[sdif]"
)

# Short UI templates need regex handling even though they have little literal
# text. Other short templates are intentionally left out to avoid overly broad
# regexes and excessive XUnity startup cost.
FORCED_RUNTIME_KEYS = {
    "${1}%:JOB",
    "BASE:${1}%",
    "Reach Lv. @{1} to Unlock New Main Quests",
}

# The known basic-attack description from the reported screenshot. Keeping it
# here also makes --check fail if future generator changes stop covering it.
KNOWN_SKILL_TEMPLATE = (
    "Deals Physical ATK*^{1}${2}%+${3}^{2} as Neutral melee Physical damage "
    "to the targeted ST enemy within ${1}m."
)

KNOWN_TOOLTIP_TEMPLATE = (
    "While 【Cloaking】 is active, you cannot be seen or targeted. "
    "You are revealed after taking damage @{1} times or dealing damage."
)

KNOWN_ATTRIBUTE_TOOLTIP_TEMPLATE = (
    "Every @{1} DEX grants @{2} HIT and @{3} Cast Speed. "
    "Archers gain an Extra @{4} PATK and @{5}% PATK."
)

KNOWN_EVENT_TEMPLATE = (
    "Every @{1} seconds, Monsters will cause trouble. Defeat them to earn rewards. "
    "Draw First Prize during the final @{2} minutes."
)

KNOWN_EVENT_TITLE = "Opening: First-Prize Drawing"
KNOWN_CALLOUT = "Endure"
KNOWN_RICH_LABEL = "<color=#9ae35a>[Party Blessing]</color>"
KNOWN_RICH_STATUS = "<color=#9ae35a>Reward Count limit reached</color>"
KNOWN_MAIN_QUEST_MARKER = "^{1}[Main Quest]^{2}"
KNOWN_SIDE_QUEST_MARKER = "^{1}[Side Quest]^{2}"
KNOWN_COMMISSION_QUEST_MARKER = "^{1}[Commission]^{2}"
KNOWN_MAIN_QUEST_TITLE = "Job Advance Training"
KNOWN_SIDE_QUEST_TITLE = "Learn About Auto-Battle"
KNOWN_WORLD_LABELS = ("Welcome to RO3", "Picky")
KNOWN_BUILD_TEMPLATE = "Suggested Build: ${1}"
KNOWN_BUILD_NAME = "Exorciser"
KNOWN_TALK_TEMPLATE = "Talk to ${1}"
KNOWN_TALK_NAME = "Alphonse"
KNOWN_BUILD_EFFECT_TEMPLATE = (
    "^{1}^{2}【Turn Undead】^{3}^{4}'s percentage-based damage multiplier "
    "increases by ${1}%, and its fixed damage increases by ${2}."
)
KNOWN_SPIRIT_TOWER_FLOOR_TEMPLATE = "Floor ${1}"
KNOWN_SPIRIT_TOWER_CLIMB_TEMPLATE = "Climb ${1} more floors to obtain"
KNOWN_PREREQUISITE_SKILL_TEMPLATE = "Prerequisite Skill <color=#cc762a>${1}</color>"
KNOWN_SERVER_LEVEL_TEMPLATE = (
    "<color=#99FF9F>Current Server Level Cap: Lv. ${1}\\n"
    "${2}: Server Level Cap increases to Lv. ${3}</color>"
)
OBSERVED_CHOOSE_LABEL = "请选择"
OBSERVED_CHOOSE_TRANSLATION = "選択してください"
LOCALIZATION_PATCH_PREFIXES = (
    # Skill names/descriptions and linked tooltips. Some combat callouts bypass
    # XUnity after the LanguageKV lookup (for example "Focused Arrow Strike!!").
    "101102",
    "101103",
    "102203",
    # NPC/monster/world entity names used by MeshUI overhead nameplates.
    "104700",
    "105300",
    # Suggested-build effect descriptions.
    "108001",
    # Generic task/objective templates such as "Talk to ${1}".
    "111901",
    # Event/guild headings and descriptions that are sometimes preformatted.
    "124001",
    "124002",
    # Quest titles, descriptions, objective strings and quest-type markers.
    "1315",
    # Recommended-build heading, server-level dynamic label, Spirit Tower.
    "250091",
    "35031",
    "360",
)
KNOWN_WORLD_NAME_PAIRS = {
    "Piere": "ピエール",
    "Magnolia": "マグノリア",
    "Ahn Gu-ho": "アン・グホ",
}
KNOWN_LOCALIZATION_PATCH_IDS = {
    "10530000045": "Piere",
    "10530000058": "Magnolia",
    "10530000067": "Isis",
    "10470000446": "Piere",
    "10470000759": "Ahn Gu-ho",
    "10470000828": "Alphonse",
    "10470000996": "Caravan Member",
    "10110200265": "Focused Arrow Strike",
    "13150600321": "Take part in events and enjoy your adventures in this world",
    "35031": KNOWN_SERVER_LEVEL_TEMPLATE,
}


class ImportErrorWithContext(RuntimeError):
    pass


def protected_tokens(text: str) -> Counter[str]:
    return Counter(PROTECTED_RE.findall(text))


def validate_translation(source: str, translated: str, context: str) -> None:
    expected = protected_tokens(source)
    actual = protected_tokens(translated)
    if expected != actual:
        missing = expected - actual
        extra = actual - expected
        raise ImportErrorWithContext(
            f"{context}: protected token mismatch; missing={dict(missing)}, extra={dict(extra)}"
        )


def read_manifest() -> list[dict]:
    with MANIFEST.open("r", encoding="utf-8") as handle:
        manifest = json.load(handle)
    parts = [int(item["part"]) for item in manifest]
    if parts != list(range(1, 28)):
        raise ImportErrorWithContext(
            f"manifest must contain parts 1..27 exactly; got {parts}"
        )
    return manifest


def read_split_files() -> tuple[dict[str, str], dict[int, str], int, int]:
    translations: dict[str, str] = {}
    index_to_english: dict[int, str] = {}
    total_rows = 0
    duplicate_overrides = 0

    for item in read_manifest():
        path = SPLIT_DIR / item["filename"]
        if not path.is_file():
            raise ImportErrorWithContext(f"missing split file: {path}")

        with path.open("r", encoding="utf-8-sig", newline="") as handle:
            reader = csv.DictReader(handle, delimiter="\t")
            if reader.fieldnames != ["Index", "English", "Japanese_Translation"]:
                raise ImportErrorWithContext(
                    f"{path.name}: expected exactly 3 TSV columns, got {reader.fieldnames}"
                )
            rows = list(reader)

        expected_items = int(item["items"])
        if len(rows) != expected_items:
            raise ImportErrorWithContext(
                f"{path.name}: expected {expected_items} rows, got {len(rows)}"
            )

        for row_number, row in enumerate(rows, start=2):
            try:
                index = int(row["Index"])
            except (TypeError, ValueError) as exc:
                raise ImportErrorWithContext(
                    f"{path.name}:{row_number}: invalid Index {row.get('Index')!r}"
                ) from exc

            english = row["English"] or ""
            japanese = row["Japanese_Translation"] or ""
            if not english:
                raise ImportErrorWithContext(
                    f"{path.name}:{row_number}: English is empty"
                )
            index_to_english[index] = english
            total_rows += 1

            if not japanese:
                continue

            validate_translation(english, japanese, f"{path.name}:{row_number}")
            if english in translations and translations[english] != japanese:
                duplicate_overrides += 1
            # The later TSV row wins deterministically, matching normal import
            # override semantics for duplicate English keys.
            translations[english] = japanese

    expected_indexes = set(range(1, 26616))
    actual_indexes = set(index_to_english)
    if actual_indexes != expected_indexes:
        missing = sorted(expected_indexes - actual_indexes)[:20]
        extra = sorted(actual_indexes - expected_indexes)[:20]
        raise ImportErrorWithContext(
            f"split indexes are not exactly 1..26615; missing={missing}, extra={extra}"
        )

    return translations, index_to_english, total_rows, duplicate_overrides


def iter_import_pairs(path: Path, index_to_english: dict[int, str]):
    """Yield (English, Japanese) pairs from a user import file."""
    text = path.read_text(encoding="utf-8-sig")
    lines = [line for line in text.splitlines() if line.strip() and not line.lstrip().startswith("#")]
    if not lines:
        return

    # Header-style TSV from split_1000 or external translation tools.
    if lines[0].split("\t")[:3] == ["Index", "English", "Japanese_Translation"]:
        reader = csv.DictReader(lines, delimiter="\t")
        for row in reader:
            english = row.get("English") or ""
            japanese = row.get("Japanese_Translation") or ""
            if english and japanese:
                yield english, japanese
        return

    for line_number, line in enumerate(lines, start=1):
        cols = line.split("\t")
        if len(cols) >= 3 and cols[0].isdigit():
            english = cols[1]
            japanese = "\t".join(cols[2:])
        elif len(cols) >= 2:
            left = cols[0]
            japanese = "\t".join(cols[1:])
            if left.isdigit():
                index = int(left)
                if index not in index_to_english:
                    raise ImportErrorWithContext(
                        f"{path.name}:{line_number}: unknown Index {index}"
                    )
                english = index_to_english[index]
            else:
                english = left
        elif "=" in line:
            # Compatibility with simple XUnity-style manual import lines.
            english, japanese = line.split("=", 1)
        else:
            raise ImportErrorWithContext(
                f"{path.name}:{line_number}: unsupported import line format"
            )

        english = english.strip("\ufeff")
        if english and japanese:
            yield english, japanese


def apply_import_overrides(
    translations: dict[str, str], index_to_english: dict[int, str]
) -> tuple[int, int]:
    imported_pairs = 0
    changed_pairs = 0
    if not IMPORT_DIR.is_dir():
        return imported_pairs, changed_pairs

    for path in sorted(IMPORT_DIR.iterdir()):
        if not path.is_file() or path.suffix.lower() not in {".tsv", ".txt"}:
            continue
        for english, japanese in iter_import_pairs(path, index_to_english):
            validate_translation(english, japanese, f"import/{path.name}")
            imported_pairs += 1
            if translations.get(english) != japanese:
                changed_pairs += 1
            translations[english] = japanese
    return imported_pairs, changed_pairs


def _regex_escape_plain(text: str) -> str:
    # Escape .NET regex metacharacters, but keep normal spaces readable.
    return re.sub(r"([\\.^$|?*+()\[\]{}])", r"\\\1", text)


def regex_escape_literal(text: str) -> str:
    """Escape a literal while accepting the game's tooltip bracket variant.

    LanguageKV uses corner brackets (【Name】), but linked skill/effect tooltips
    are rendered as ASCII square brackets ([Name]) before XUnity receives the
    text. Accept either representation so a single canonical TSV entry covers
    both paths.
    """
    pieces: list[str] = []
    cursor = 0
    for match in re.finditer(r"【([^】]+)】", text):
        pieces.append(_regex_escape_plain(text[cursor : match.start()]))
        inner = _regex_escape_plain(match.group(1))
        pieces.append(r"(?:【" + inner + r"】|\[" + inner + r"\])")
        cursor = match.end()
    pieces.append(_regex_escape_plain(text[cursor:]))
    return "".join(pieces)


def runtime_group_name(token: str, occurrence: int) -> str:
    kind = "v"
    if token.startswith("^{"):
        kind = "style"
    elif token.startswith("@{"):
        kind = "at"
    elif token.startswith("${"):
        kind = "dollar"
    elif token.startswith("{"):
        kind = "fmt"
    elif token.startswith("%"):
        kind = "printf"
    digits = "".join(ch for ch in token if ch.isdigit()) or str(occurrence)
    return f"ro3_{kind}_{digits}_{occurrence}_i"


def build_runtime_regex(source: str, translated: str, *, force: bool = False) -> str | None:
    matches = list(RUNTIME_TOKEN_RE.finditer(source))
    if not matches:
        return None

    # XUnity 5.6.2's translation-file parser treats quote-bearing regex
    # key/value pairs as quoted fields and rejects some otherwise valid rules.
    # These are rare; keep their canonical exact translations and skip only the
    # runtime-regex derivative instead of emitting a file that logs parse errors.
    if '"' in source or '"' in translated:
        return None

    # Avoid broad regexes such as a single placeholder or very short generic
    # labels. Known compact HUD templates are explicitly allowed above.
    literal = RUNTIME_TOKEN_RE.sub("", source)
    literal_letters = sum(ch.isalpha() for ch in literal)
    if not force and source not in FORCED_RUNTIME_KEYS and literal_letters < 12:
        return None

    pieces: list[str] = ["^"]
    token_groups: dict[str, str] = {}
    cursor = 0
    occurrence = 0
    for match in matches:
        pieces.append(regex_escape_literal(source[cursor : match.start()]))
        token = match.group(0)
        occurrence += 1
        if token in token_groups:
            pieces.append(rf"\k<{token_groups[token]}>")
        else:
            group = runtime_group_name(token, occurrence)
            token_groups[token] = group
            if token.startswith("^{"):
                # Styling placeholders become zero or more TMP rich-text tags
                # before the string reaches XUnity. Empty also covers cases
                # where XUnity has already stripped rich text for lookup.
                pieces.append(rf"(?<{group}>(?:<[^>]+>)*)")
            else:
                pieces.append(rf"(?<{group}>[\s\S]+?)")
        cursor = match.end()
    pieces.append(regex_escape_literal(source[cursor:]))
    pieces.append("$")
    pattern = "".join(pieces)

    replacement = translated
    for token, group in sorted(token_groups.items(), key=lambda kv: -len(kv[0])):
        replacement = replacement.replace(token, "${" + group + "}")

    # Quotes delimit regex keys in XUnity manual files.
    pattern = pattern.replace('"', r'\"')
    return f'r:"{pattern}"={replacement}'


def load_language_kv_rows(prefixes: tuple[str, ...]) -> list[tuple[str, str]]:
    """Return ``(ID, English)`` rows whose LanguageKV IDs match prefixes."""
    if not LANGUAGE_KV_FILE.is_file():
        raise ImportErrorWithContext(f"missing LanguageKV source: {LANGUAGE_KV_FILE}")
    result: list[tuple[str, str]] = []
    with LANGUAGE_KV_FILE.open("r", encoding="utf-8-sig") as handle:
        for line_number, line in enumerate(handle, start=1):
            line = line.rstrip("\r\n")
            if not line:
                continue
            try:
                key, english = line.split("\t", 1)
            except ValueError as exc:
                raise ImportErrorWithContext(
                    f"{LANGUAGE_KV_FILE.name}:{line_number}: expected ID<TAB>English"
                ) from exc
            if key.startswith(prefixes):
                result.append((key, english))
    return result


def load_language_kv_texts(prefixes: tuple[str, ...]) -> list[str]:
    """Return unique LanguageKV English texts in stable source-file order."""
    return list(dict.fromkeys(english for _, english in load_language_kv_rows(prefixes)))


def load_runtime_keys() -> set[str]:
    """Return texts known to have placeholders expanded before XUnity lookup.

    IDs beginning with 100105 are character-attribute display/tooltip records;
    their numeric placeholders are expanded before hover tooltips reach XUnity.
    IDs beginning with 101103 are skill-description records. IDs beginning
    with 102203 are linked skill/effect tooltip records. IDs beginning with
    108001 are recommended-build synergy descriptions, and 250091 is the
    recommended-build heading. The compact 360xx namespace is the Spirit Tower
    UI; several of its labels (for example ``Floor ${1}`` and
    ``Climb ${1} more floors to obtain``) are expanded before XUnity receives
    them. Restricting runtime regexes to these namespaces plus 360xx avoids
    loading thousands of unrelated rules while still covering the known
    game-side expansions.
    """
    return set(
        load_language_kv_texts(
            (
                "100105",
                "101103",
                "102203",
                "108001",
                "124002",
                "131501",
                "250091",
                "33001",
                "35031",
                "360",
            )
        )
    )


def build_runtime_regex_lines(translations: dict[str, str]) -> list[str]:
    runtime_keys = load_runtime_keys()
    lines: list[str] = []
    for english, japanese in translations.items():
        if english not in runtime_keys and english not in FORCED_RUNTIME_KEYS:
            continue
        line = build_runtime_regex(english, japanese, force=True)
        if line:
            lines.append(line)

        # A number of UI paths strip TMP rich-text before the runtime-expanded
        # string reaches XUnity. Priority exact variants cannot match after the
        # placeholders have already been expanded, so emit a regex derivative
        # from the same canonical pair when rich text is present.
        plain_english = strip_rich_text(english)
        if plain_english != english:
            plain_japanese = strip_rich_text(japanese)
            line = build_runtime_regex(plain_english, plain_japanese, force=True)
            if line:
                lines.append(line)

    # ID 35031 is authored as one rich-text block with a literal "\\n", but the
    # task/server HUD renders its two lines as separate TextMeshPro strings. The
    # live values therefore never match either the canonical exact key or the
    # full multiline runtime regex. Derive both rendered lines directly from the
    # canonical template, plus a date-less second-line form used by some layouts.
    server_japanese = translations.get(KNOWN_SERVER_LEVEL_TEMPLATE)
    if server_japanese:
        server_plain = strip_rich_text(KNOWN_SERVER_LEVEL_TEMPLATE)
        server_japanese_plain = strip_rich_text(server_japanese)
        server_parts = server_plain.split("\\n")
        server_japanese_parts = server_japanese_plain.split("\\n")
        if len(server_parts) == 2 and len(server_japanese_parts) == 2:
            for english, japanese in zip(server_parts, server_japanese_parts):
                line = build_runtime_regex(english, japanese, force=True)
                if line:
                    lines.append(line)

            second_source = server_parts[1]
            second_japanese = server_japanese_parts[1]
            if second_source.startswith("${2}: ") and second_japanese.startswith("${2}："):
                line = build_runtime_regex(
                    second_source[len("${2}: ") :],
                    second_japanese[len("${2}：") :],
                    force=True,
                )
                if line:
                    lines.append(line)

    # The task HUD can concatenate a quest-type marker and a placeholder-bearing
    # quest title after expanding the title's runtime values. Exact combined
    # variants cannot cover strings such as
    # "[Main Quest] Reach Lv. 40 to Unlock New Main Quests", so emit combined
    # regexes for all 131501 placeholder titles and all three observed markers.
    quest_markers = (
        KNOWN_MAIN_QUEST_MARKER,
        KNOWN_SIDE_QUEST_MARKER,
        KNOWN_COMMISSION_QUEST_MARKER,
    )
    quest_titles = load_language_kv_texts(("131501",))
    for marker in quest_markers:
        marker_japanese = translations.get(marker)
        if not marker_japanese:
            continue
        marker_plain = strip_style_placeholders(marker)
        marker_japanese_plain = strip_style_placeholders(marker_japanese)
        for english in quest_titles:
            if not RUNTIME_TOKEN_RE.search(english):
                continue
            japanese = translations.get(english)
            if not japanese:
                continue
            line = build_runtime_regex(
                f"{marker_plain} {english}",
                f"{marker_japanese_plain} {japanese}",
                force=True,
            )
            if line:
                lines.append(line)

    # 131506 objective strings use a trailing '*' as a game-side progress
    # marker. The HUD removes the '*' and appends a runtime counter such as
    # "0/1" or "0/15". Synthesize that rendered form from canonical data.
    for english in load_language_kv_texts(("131506",)):
        japanese = translations.get(english)
        if not japanese or not english.endswith("*") or not japanese.endswith("*"):
            continue
        line = build_runtime_regex(
            english[:-1].rstrip() + " ${1}",
            japanese[:-1].rstrip() + " ${1}",
            force=True,
        )
        if line:
            lines.append(line)

    # Generic talk objectives are materialized with an NPC name before XUnity
    # and can then receive a progress counter. Generate exact NPC-name regexes
    # from 104700 so both the NPC name and the counter are preserved without
    # enabling global partial translation.
    talk_template_translation = translations.get(KNOWN_TALK_TEMPLATE)
    if talk_template_translation:
        for npc_name in load_language_kv_texts(("104700",)):
            translated_npc_name = translations.get(npc_name)
            if not translated_npc_name or translated_npc_name == npc_name:
                continue
            line = build_runtime_regex(
                KNOWN_TALK_TEMPLATE.replace("${1}", npc_name) + " ${2}",
                talk_template_translation.replace("${1}", translated_npc_name) + " ${2}",
                force=True,
            )
            if line:
                lines.append(line)

    # Preserve deterministic order while discarding duplicate derivatives.
    lines = list(dict.fromkeys(lines))
    return lines


def strip_rich_text(text: str) -> str:
    return re.sub(r"<[^>]+>", "", text)


def strip_style_placeholders(text: str) -> str:
    """Remove RO3's non-value style placeholders such as ^{1} and ^{2}."""
    return re.sub(r"\^\{\d+\}", "", text)


def build_priority_override_lines(translations: dict[str, str]) -> list[str]:
    """Build exact runtime variants that differ from canonical LanguageKV text.

    RO3 sometimes strips TMP rich-text tags before XUnity sees a string, wraps
    event headings in square brackets, or appends exclamation marks to skill
    names for combat speech bubbles. Generate these derivatives from the same
    canonical split_1000 translations so they stay in sync with future edits.
    """
    variants: dict[str, str] = {}
    conflicts: set[str] = set()

    def add_variant(source: str, translated: str) -> None:
        if not source or source == translated or "=" in source or "\n" in source:
            return
        previous = variants.get(source)
        if previous is None:
            variants[source] = translated
        elif previous != translated:
            conflicts.add(source)

    # XUnity's bundled static cache contains JOB=仕事. An exact identity pair
    # JOB=JOB is not sufficient to defeat that built-in entry in an already
    # running process, so keep a visually zero-width non-identity override.
    variants["JOB"] = "JOB\u200b"

    # The game frequently removes <color>/<size>/other TMP tags before handing
    # text to XUnity. Add the plain-text form when it is unambiguous.
    for english, japanese in translations.items():
        plain_english = strip_rich_text(english)
        if plain_english != english:
            add_variant(plain_english, strip_rich_text(japanese))

        # Some UI labels also remove RO3's ^{n} style placeholders before the
        # TextMeshPro setter is reached. These placeholders carry no runtime
        # value, so stripping them on both sides is safe when the result is
        # unambiguous. This covers labels such as [Main Quest]/[Side Quest].
        style_plain_english = strip_style_placeholders(english)
        if style_plain_english != english:
            add_variant(style_plain_english, strip_style_placeholders(japanese))

    # Party event headings in the HUD are wrapped in [] by the Lua/UI layer.
    for english in load_language_kv_texts(("124001",)):
        japanese = translations.get(english)
        if japanese:
            add_variant(f"[{english}]", f"[{japanese}]")

    # The task HUD can concatenate a styled quest-type marker and a quest title
    # into one TextMeshPro string, after stripping the ^{n} style placeholders.
    # Generate exact combined forms for the quest-title namespace so both the
    # prefix and title are translated in one lookup.
    main_marker = strip_style_placeholders(KNOWN_MAIN_QUEST_MARKER)
    main_marker_jp = strip_style_placeholders(translations.get(KNOWN_MAIN_QUEST_MARKER, ""))
    side_marker = strip_style_placeholders(KNOWN_SIDE_QUEST_MARKER)
    side_marker_jp = strip_style_placeholders(translations.get(KNOWN_SIDE_QUEST_MARKER, ""))
    commission_marker = strip_style_placeholders(KNOWN_COMMISSION_QUEST_MARKER)
    commission_marker_jp = strip_style_placeholders(
        translations.get(KNOWN_COMMISSION_QUEST_MARKER, "")
    )
    for english in load_language_kv_texts(("131501",)):
        japanese = translations.get(english)
        if not japanese:
            continue
        if main_marker_jp:
            add_variant(f"{main_marker} {english}", f"{main_marker_jp} {japanese}")
        if side_marker_jp:
            add_variant(f"{side_marker} {english}", f"{side_marker_jp} {japanese}")
        if commission_marker_jp:
            add_variant(
                f"{commission_marker} {english}",
                f"{commission_marker_jp} {japanese}",
            )

    # A few world-space labels are repeatedly rewritten by the game. Keep
    # their canonical translations in the highest-priority manual file too.
    for english in load_language_kv_texts(("105300", "181")):
        japanese = translations.get(english)
        if japanese:
            add_variant(english, japanese)

    # Combat speech bubbles append punctuation to the 101102 skill name after
    # the localization lookup. Generate the observed forms up front.
    for english in load_language_kv_texts(("101102",)):
        japanese = translations.get(english)
        if japanese:
            add_variant(f"{english}!", f"{japanese}!")
            add_variant(f"{english}!!", f"{japanese}!!")

    # The recommended-build heading receives its build name after the normal
    # LanguageKV lookup. A regex can translate the label, but its captured
    # build name would stay English. Generate exact complete strings from the
    # 115200 build-name namespace so both pieces use split_1000 translations.
    build_template_translation = translations.get(KNOWN_BUILD_TEMPLATE)
    if build_template_translation:
        for build_name in load_language_kv_texts(("115200",)):
            translated_build_name = translations.get(build_name)
            if translated_build_name:
                add_variant(
                    KNOWN_BUILD_TEMPLATE.replace("${1}", build_name),
                    build_template_translation.replace("${1}", translated_build_name),
                )

    # Some quest objectives are built from the generic "Talk to ${1}"
    # template after the NPC name has already been resolved to English. XUnity
    # therefore sees strings such as "Talk to Alphonse" rather than the
    # canonical placeholder form. Generate complete variants from the same
    # 104700 world-entity names used by the overhead-name fallback so the NPC
    # name itself is translated too.
    talk_template_translation = translations.get(KNOWN_TALK_TEMPLATE)
    if talk_template_translation:
        for npc_name in load_language_kv_texts(("104700",)):
            translated_npc_name = translations.get(npc_name)
            if translated_npc_name and translated_npc_name != npc_name:
                add_variant(
                    KNOWN_TALK_TEMPLATE.replace("${1}", npc_name),
                    talk_template_translation.replace("${1}", translated_npc_name),
                )

    # This recommended-build screen contains one Simplified-Chinese prompt
    # that bypasses the English LanguageKV table entirely. Keep the observed
    # runtime alias in the priority file so the surrounding UI is consistent.
    add_variant(OBSERVED_CHOOSE_LABEL, OBSERVED_CHOOSE_TRANSLATION)

    for source in conflicts:
        variants.pop(source, None)

    header = [
        "// RO3 high-priority runtime collision/variant overrides",
        "// Generated by _TranslationWorkspace/import_translations.py",
        "// U+200B after JOB is intentional and renders with zero width.",
        f"// Variants: {len(variants)}; ambiguous stripped variants skipped: {len(conflicts)}",
        "// -----------------------------------------------------",
    ]
    return header + [f"{key}={value}" for key, value in sorted(variants.items())]


def build_localization_patch_lines(translations: dict[str, str]) -> list[str]:
    """Build ID-aware overrides for runtime paths that bypass XUnity setters.

    The production client exposes ``Localization_en`` through its Lua runtime.
    Several MeshUI/task/callout paths consume that table upstream and never pass
    the final rendered text through a setter that XUnity 5.6.2 can reliably
    hook. Keep this map ID-aware so duplicate English strings remain distinct,
    and verify the expected English value at runtime before replacing it.
    """
    lines = [
        "# RO3 runtime Localization_en overrides",
        "# Generated by _TranslationWorkspace/import_translations.py",
        "# ID<TAB>English<TAB>Japanese; canonical source is split_1000 parts 01-27",
    ]
    for key, english in load_language_kv_rows(LOCALIZATION_PATCH_PREFIXES):
        japanese = translations.get(english)
        if not japanese or japanese == english:
            continue
        if (
            "\t" in key
            or "\t" in english
            or "\n" in english
            or "\t" in japanese
            or "\n" in japanese
        ):
            continue
        lines.append(f"{key}\t{english}\t{japanese}")
    return lines


def atomic_write_text(path: Path, text: str, encoding: str = "utf-8-sig") -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temp_name = tempfile.mkstemp(prefix=path.name + ".", suffix=".tmp", dir=str(path.parent))
    try:
        with os.fdopen(fd, "w", encoding=encoding, newline="\n") as handle:
            handle.write(text)
        os.replace(temp_name, path)
    except Exception:
        try:
            os.unlink(temp_name)
        except OSError:
            pass
        raise


def backup_if_exists(path: Path, timestamp: str) -> None:
    if not path.is_file() or path.stat().st_size == 0:
        return
    backup = path.with_name(f"{path.name}.before-import-{timestamp}.bak")
    shutil.copy2(path, backup)


def write_outputs(
    translations: dict[str, str],
    regex_lines: list[str],
    priority_override_lines: list[str],
    localization_patch_lines: list[str],
) -> None:
    timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    backup_if_exists(OUTPUT_FILE, timestamp)
    backup_if_exists(CANONICAL_MANUAL_FILE, timestamp)
    backup_if_exists(PRIORITY_OVERRIDE_FILE, timestamp)
    backup_if_exists(RUNTIME_REGEX_FILE, timestamp)
    backup_if_exists(LOCALIZATION_PATCH_FILE, timestamp)

    dictionary_lines = [
        "// RO3 Asia Master Japanese Translation Dictionary",
        f"// Total active translations: {len(translations)}",
        "// Canonical source: _TranslationWorkspace/split_1000 parts 01-27",
        "// -----------------------------------------------------",
    ]
    dictionary_lines.extend(f"{key}={value}" for key, value in sorted(translations.items()))
    dictionary_text = "\n".join(dictionary_lines) + "\n"
    atomic_write_text(OUTPUT_FILE, dictionary_text)
    # XUnity gives its configured OutputFile the lowest translation priority.
    # Keep a second, non-output manual file so the canonical split_1000 values
    # override XUnity's bundled static dictionary (for example JOB=仕事).
    atomic_write_text(CANONICAL_MANUAL_FILE, dictionary_text)

    atomic_write_text(PRIORITY_OVERRIDE_FILE, "\n".join(priority_override_lines) + "\n")

    regex_header = [
        "// RO3 runtime placeholder translations",
        "// Generated by _TranslationWorkspace/import_translations.py",
        "// This file must NOT start with '_' because XUnity ignores regexes there.",
        f"// Rules: {len(regex_lines)}",
        "// -----------------------------------------------------",
    ]
    atomic_write_text(RUNTIME_REGEX_FILE, "\n".join(regex_header + regex_lines) + "\n")
    atomic_write_text(
        LOCALIZATION_PATCH_FILE,
        "\n".join(localization_patch_lines) + "\n",
    )

    cache_text = json.dumps(translations, ensure_ascii=False, indent=1, sort_keys=True) + "\n"
    atomic_write_text(CACHE_FILE, cache_text, encoding="utf-8")


def configure_xunity() -> tuple[bool, bool, bool, bool, bool]:
    if not CONFIG_FILE.is_file():
        return False, False, False, False, False
    text = CONFIG_FILE.read_text(encoding="utf-8-sig")
    updated, reload_count = re.subn(
        r"(?m)^ReloadTranslationsOnFileChange\s*=\s*False\s*$",
        "ReloadTranslationsOnFileChange=True",
        text,
    )
    updated, static_count = re.subn(
        r"(?m)^UseStaticTranslations\s*=\s*True\s*$",
        "UseStaticTranslations=False",
        updated,
    )
    updated, getter_count = re.subn(
        r"(?m)^TextGetterCompatibilityMode\s*=\s*False\s*$",
        "TextGetterCompatibilityMode=True",
        updated,
    )

    # Partial translations generate a very large substring cache and can turn
    # short keybind/HUD strings into unrelated translated fragments. Runtime
    # values are covered by our generated regex rules, so prefer exact/regex
    # matching and keep one-character controls untouched.
    updated, partial_count = re.subn(
        r"(?m)^GeneratePartialTranslations\s*=\s*True\s*$",
        "GeneratePartialTranslations=False",
        updated,
    )

    # Preserve the game's original TMP font so custom/private-use glyphs used
    # by keybind labels keep their intended appearance. The Japanese TMP asset
    # is installed as a fallback instead of replacing every TextMeshPro font.
    updated, override_tmp_count = re.subn(
        r"(?m)^OverrideFontTextMeshPro\s*=.*$",
        "OverrideFontTextMeshPro=",
        updated,
    )
    updated, fallback_tmp_count = re.subn(
        r"(?m)^FallbackFontTextMeshPro\s*=.*$",
        "FallbackFontTextMeshPro=arialuni_sdf_u2022",
        updated,
    )

    if (
        reload_count
        or static_count
        or getter_count
        or partial_count
        or override_tmp_count
        or fallback_tmp_count
    ):
        atomic_write_text(CONFIG_FILE, updated)
    hot_reload = "ReloadTranslationsOnFileChange=True" in updated
    static_disabled = "UseStaticTranslations=False" in updated
    getter_compat = "TextGetterCompatibilityMode=True" in updated
    partial_disabled = "GeneratePartialTranslations=False" in updated
    tmp_fallback = (
        re.search(r"(?m)^OverrideFontTextMeshPro\s*=\s*$", updated) is not None
        and "FallbackFontTextMeshPro=arialuni_sdf_u2022" in updated
    )
    return hot_reload, static_disabled, getter_compat, partial_disabled, tmp_fallback


def run(check_only: bool) -> int:
    translations, index_to_english, total_rows, duplicate_overrides = read_split_files()
    imported_pairs, changed_pairs = apply_import_overrides(translations, index_to_english)
    regex_lines = build_runtime_regex_lines(translations)
    priority_override_lines = build_priority_override_lines(translations)
    localization_patch_lines = build_localization_patch_lines(translations)

    if translations.get("JOB") != "JOB":
        raise ImportErrorWithContext(
            f"canonical JOB translation must be 'JOB', got {translations.get('JOB')!r}"
        )
    if KNOWN_SKILL_TEMPLATE not in translations:
        raise ImportErrorWithContext("known basic-attack skill template is missing from translations")
    known_regex = build_runtime_regex(
        KNOWN_SKILL_TEMPLATE, translations[KNOWN_SKILL_TEMPLATE], force=True
    )
    if not known_regex or known_regex not in regex_lines:
        raise ImportErrorWithContext("known basic-attack skill template did not generate a regex rule")
    if KNOWN_TOOLTIP_TEMPLATE not in translations:
        raise ImportErrorWithContext("known Cloaking tooltip template is missing from translations")
    known_tooltip_regex = build_runtime_regex(
        KNOWN_TOOLTIP_TEMPLATE, translations[KNOWN_TOOLTIP_TEMPLATE], force=True
    )
    if not known_tooltip_regex or known_tooltip_regex not in regex_lines:
        raise ImportErrorWithContext("known Cloaking tooltip template did not generate a regex rule")
    if KNOWN_ATTRIBUTE_TOOLTIP_TEMPLATE not in translations:
        raise ImportErrorWithContext("known DEX attribute tooltip template is missing from translations")
    known_attribute_tooltip_regex = build_runtime_regex(
        KNOWN_ATTRIBUTE_TOOLTIP_TEMPLATE,
        translations[KNOWN_ATTRIBUTE_TOOLTIP_TEMPLATE],
        force=True,
    )
    if not known_attribute_tooltip_regex or known_attribute_tooltip_regex not in regex_lines:
        raise ImportErrorWithContext("known DEX attribute tooltip template did not generate a regex rule")
    if KNOWN_EVENT_TEMPLATE not in translations:
        raise ImportErrorWithContext("known party-event template is missing from translations")
    known_event_regex = build_runtime_regex(
        KNOWN_EVENT_TEMPLATE, translations[KNOWN_EVENT_TEMPLATE], force=True
    )
    if not known_event_regex or known_event_regex not in regex_lines:
        raise ImportErrorWithContext("known party-event template did not generate a regex rule")
    if KNOWN_BUILD_EFFECT_TEMPLATE not in translations:
        raise ImportErrorWithContext("known recommended-build effect template is missing from translations")
    known_build_effect_regex = build_runtime_regex(
        KNOWN_BUILD_EFFECT_TEMPLATE,
        translations[KNOWN_BUILD_EFFECT_TEMPLATE],
        force=True,
    )
    if not known_build_effect_regex or known_build_effect_regex not in regex_lines:
        raise ImportErrorWithContext(
            "known recommended-build effect template did not generate a regex rule"
        )
    for known_tower_template in (
        KNOWN_SPIRIT_TOWER_FLOOR_TEMPLATE,
        KNOWN_SPIRIT_TOWER_CLIMB_TEMPLATE,
    ):
        if known_tower_template not in translations:
            raise ImportErrorWithContext(
                f"known Spirit Tower template is missing from translations: {known_tower_template!r}"
            )
        known_tower_regex = build_runtime_regex(
            known_tower_template,
            translations[known_tower_template],
            force=True,
        )
        if not known_tower_regex or known_tower_regex not in regex_lines:
            raise ImportErrorWithContext(
                f"known Spirit Tower template did not generate a regex rule: {known_tower_template!r}"
            )

    prerequisite_japanese = translations.get(KNOWN_PREREQUISITE_SKILL_TEMPLATE)
    if not prerequisite_japanese:
        raise ImportErrorWithContext("known prerequisite-skill template is missing from translations")
    prerequisite_plain = strip_rich_text(KNOWN_PREREQUISITE_SKILL_TEMPLATE)
    prerequisite_japanese_plain = strip_rich_text(prerequisite_japanese)
    prerequisite_regex = build_runtime_regex(
        prerequisite_plain,
        prerequisite_japanese_plain,
        force=True,
    )
    if not prerequisite_regex or prerequisite_regex not in regex_lines:
        raise ImportErrorWithContext(
            "known prerequisite-skill rendered template did not generate a runtime regex"
        )
    server_japanese = translations.get(KNOWN_SERVER_LEVEL_TEMPLATE)
    if not server_japanese:
        raise ImportErrorWithContext("known server-level template is missing from translations")
    server_parts = strip_rich_text(KNOWN_SERVER_LEVEL_TEMPLATE).split("\\n")
    server_japanese_parts = strip_rich_text(server_japanese).split("\\n")
    if len(server_parts) != 2 or len(server_japanese_parts) != 2:
        raise ImportErrorWithContext("known server-level template did not split into two rendered lines")
    for english, japanese in zip(server_parts, server_japanese_parts):
        server_regex = build_runtime_regex(english, japanese, force=True)
        if not server_regex or server_regex not in regex_lines:
            raise ImportErrorWithContext(
                f"known server-level rendered line did not generate a regex rule: {english!r}"
            )

    priority_text = "\n".join(priority_override_lines)
    expected_priority_pairs = {
        f"[{KNOWN_EVENT_TITLE}]": f"[{translations[KNOWN_EVENT_TITLE]}]",
        strip_rich_text(KNOWN_RICH_LABEL): strip_rich_text(translations[KNOWN_RICH_LABEL]),
        strip_rich_text(KNOWN_RICH_STATUS): strip_rich_text(translations[KNOWN_RICH_STATUS]),
        f"{KNOWN_CALLOUT}!!": f"{translations[KNOWN_CALLOUT]}!!",
        strip_style_placeholders(KNOWN_MAIN_QUEST_MARKER): strip_style_placeholders(
            translations[KNOWN_MAIN_QUEST_MARKER]
        ),
        strip_style_placeholders(KNOWN_SIDE_QUEST_MARKER): strip_style_placeholders(
            translations[KNOWN_SIDE_QUEST_MARKER]
        ),
        strip_style_placeholders(KNOWN_COMMISSION_QUEST_MARKER): strip_style_placeholders(
            translations[KNOWN_COMMISSION_QUEST_MARKER]
        ),
        f"{strip_style_placeholders(KNOWN_MAIN_QUEST_MARKER)} {KNOWN_MAIN_QUEST_TITLE}": (
            f"{strip_style_placeholders(translations[KNOWN_MAIN_QUEST_MARKER])} "
            f"{translations[KNOWN_MAIN_QUEST_TITLE]}"
        ),
        f"{strip_style_placeholders(KNOWN_SIDE_QUEST_MARKER)} {KNOWN_SIDE_QUEST_TITLE}": (
            f"{strip_style_placeholders(translations[KNOWN_SIDE_QUEST_MARKER])} "
            f"{translations[KNOWN_SIDE_QUEST_TITLE]}"
        ),
        KNOWN_BUILD_TEMPLATE.replace("${1}", KNOWN_BUILD_NAME): translations[
            KNOWN_BUILD_TEMPLATE
        ].replace("${1}", translations[KNOWN_BUILD_NAME]),
        KNOWN_TALK_TEMPLATE.replace("${1}", KNOWN_TALK_NAME): translations[
            KNOWN_TALK_TEMPLATE
        ].replace("${1}", translations[KNOWN_TALK_NAME]),
        OBSERVED_CHOOSE_LABEL: OBSERVED_CHOOSE_TRANSLATION,
    }
    for source in KNOWN_WORLD_LABELS:
        expected_priority_pairs[source] = translations[source]
    for source, translated in expected_priority_pairs.items():
        if f"{source}={translated}" not in priority_text:
            raise ImportErrorWithContext(
                f"known runtime variant did not generate: {source!r} -> {translated!r}"
            )

    localization_patch_text = "\n".join(localization_patch_lines)
    for source, expected in KNOWN_WORLD_NAME_PAIRS.items():
        actual = translations.get(source)
        if actual != expected:
            raise ImportErrorWithContext(
                f"known world name translation changed: {source!r} -> {actual!r}; expected {expected!r}"
            )
        matching_ids = [
            key
            for key, english in load_language_kv_rows(("104700", "105300"))
            if english == source
        ]
        if not matching_ids or not any(
            f"{key}\t{source}\t{expected}" in localization_patch_text
            for key in matching_ids
        ):
            raise ImportErrorWithContext(
                f"known localization-table world name did not generate: {source!r} -> {expected!r}"
            )

    language_kv_by_id = dict(load_language_kv_rows(("",)))
    for key, expected_english in KNOWN_LOCALIZATION_PATCH_IDS.items():
        actual_english = language_kv_by_id.get(key)
        if actual_english != expected_english:
            raise ImportErrorWithContext(
                f"LanguageKV regression row changed: {key} -> {actual_english!r}; "
                f"expected {expected_english!r}"
            )
        expected_japanese = translations.get(expected_english)
        if not expected_japanese:
            raise ImportErrorWithContext(
                f"known localization patch row lacks canonical Japanese: {key} {expected_english!r}"
            )
        expected_line = f"{key}\t{expected_english}\t{expected_japanese}"
        if expected_line not in localization_patch_text:
            raise ImportErrorWithContext(
                f"known localization patch row did not generate: {expected_line!r}"
            )

    if not check_only:
        write_outputs(
            translations,
            regex_lines,
            priority_override_lines,
            localization_patch_lines,
        )
        hot_reload, static_disabled, getter_compat, partial_disabled, tmp_fallback = configure_xunity()
    else:
        config_text = (
            CONFIG_FILE.read_text(encoding="utf-8-sig") if CONFIG_FILE.is_file() else ""
        )
        hot_reload = "ReloadTranslationsOnFileChange=True" in config_text
        static_disabled = "UseStaticTranslations=False" in config_text
        getter_compat = "TextGetterCompatibilityMode=True" in config_text
        partial_disabled = "GeneratePartialTranslations=False" in config_text
        tmp_fallback = (
            re.search(r"(?m)^OverrideFontTextMeshPro\s*=\s*$", config_text) is not None
            and "FallbackFontTextMeshPro=arialuni_sdf_u2022" in config_text
        )

    print("RO3 translation import validation: OK")
    print(f"  split rows:             {total_rows}")
    print(f"  active unique keys:     {len(translations)}")
    print(f"  duplicate key overrides:{duplicate_overrides}")
    print(f"  import pairs:           {imported_pairs} ({changed_pairs} changed)")
    print(f"  runtime regex rules:    {len(regex_lines)}")
    print(f"  priority variants:      {max(0, len(priority_override_lines) - 5)}")
    print(f"  localization overrides: {max(0, len(localization_patch_lines) - 3)}")
    print(f"  JOB canonical value:    {translations['JOB']}")
    print(f"  hot reload enabled:     {hot_reload}")
    print(f"  XUnity static disabled: {static_disabled}")
    print(f"  text getter compat:     {getter_compat}")
    print(f"  partial translations:   {'disabled' if partial_disabled else 'enabled'}")
    print(f"  TMP fallback font:      {tmp_fallback}")
    if check_only:
        print("  mode:                   CHECK ONLY (no files written)")
    else:
        print(f"  dictionary:             {OUTPUT_FILE}")
        print(f"  canonical manual:       {CANONICAL_MANUAL_FILE}")
        print(f"  priority overrides:     {PRIORITY_OVERRIDE_FILE}")
        print(f"  runtime regex:          {RUNTIME_REGEX_FILE}")
        print(f"  localization map:       {LOCALIZATION_PATCH_FILE}")
        print(f"  cache:                  {CACHE_FILE}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="validate inputs and generated rules without modifying files",
    )
    args = parser.parse_args()
    try:
        return run(args.check)
    except (ImportErrorWithContext, OSError, csv.Error, json.JSONDecodeError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
