param(
    [Parameter(Mandatory = $false)]
    [string]$GameRoot
)

$ErrorActionPreference = 'Stop'
$RepoRoot = Split-Path -Parent $PSScriptRoot

if ([string]::IsNullOrWhiteSpace($GameRoot)) {
    # Default for the current checkout location:
    # <RO3 Asia Launcher>\RO3_Asia_Japanese_Patch
    $GameRoot = Split-Path -Parent $RepoRoot
}

$GameRoot = [System.IO.Path]::GetFullPath($GameRoot)
$TargetClient = Join-Path $GameRoot 'Client'
$GameExe = Join-Path $TargetClient 'ro3.exe'

if (-not (Test-Path -LiteralPath $GameExe -PathType Leaf)) {
    throw "ro3.exe was not found at: $GameExe"
}

$SourceClient = Join-Path $RepoRoot 'Client'
$files = @(
    'BepInEx\Translation\ja\Text\_AutoGeneratedTranslations.txt',
    'BepInEx\Translation\ja\Text\RO3_CanonicalTranslations.txt',
    'BepInEx\Translation\ja\Text\RO3_PriorityOverrides.txt',
    'BepInEx\Translation\ja\Text\RO3_RuntimePlaceholders.txt',
    'BepInEx\config\AutoTranslatorConfig.ini',
    'arialuni_sdf_u2022'
)

foreach ($relative in $files) {
    $source = Join-Path $SourceClient $relative
    if (-not (Test-Path -LiteralPath $source -PathType Leaf)) {
        throw "Repository payload file is missing: $source"
    }

    $destination = Join-Path $TargetClient $relative
    $destinationDir = Split-Path -Parent $destination
    New-Item -ItemType Directory -Path $destinationDir -Force | Out-Null
    Copy-Item -LiteralPath $source -Destination $destination -Force
    Write-Host "[COPIED] $relative"
}

Write-Host ""
Write-Host "[OK] Japanese translation payload deployed to: $TargetClient"
Write-Host "     If RO3 is running, use XUnity reload where applicable; restart for config/font changes."
